CREATE DATABASE IF NOT EXISTS appdb
  DEFAULT CHARACTER SET utf8
  COLLATE utf8_general_ci;
USE appdb;

SET storage_engine = InnoDB;

-- USUARIOS / ROLES
CREATE TABLE IF NOT EXISTS usuarios (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  nombre VARCHAR(120) NOT NULL,
  email VARCHAR(160) NOT NULL UNIQUE,
  hash_password VARCHAR(255) NOT NULL,
  rol ENUM('ESTUDIANTE','DOCENTE','ADMIN') NOT NULL DEFAULT 'ESTUDIANTE',
  creado_en TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,  -- <-- TIMESTAMP
  activo TINYINT(1) NOT NULL DEFAULT 1
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE INDEX idx_usuarios_email ON usuarios(email);

CREATE TABLE IF NOT EXISTS estudiantes (
  usuario_id BIGINT PRIMARY KEY,
  codigo VARCHAR(40),
  CONSTRAINT fk_estudiante_usuario FOREIGN KEY (usuario_id) REFERENCES usuarios(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS docentes (
  usuario_id BIGINT PRIMARY KEY,
  titulo VARCHAR(120),
  CONSTRAINT fk_docente_usuario FOREIGN KEY (usuario_id) REFERENCES usuarios(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- CATALOGO DE MINIJUEGOS Y SUS RECURSOS
CREATE TABLE IF NOT EXISTS minijuegos (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  clave VARCHAR(30) NOT NULL UNIQUE,
  nombre VARCHAR(120) NOT NULL,
  descripcion TEXT,
  orden INT NOT NULL,
  habilitado TINYINT(1) NOT NULL DEFAULT 1
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS manuales (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  minijuego_id BIGINT NOT NULL UNIQUE,
  contenido_md MEDIUMTEXT NOT NULL,
  version VARCHAR(40),
  CONSTRAINT fk_manual_minijuego FOREIGN KEY (minijuego_id) REFERENCES minijuegos(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS videos (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  minijuego_id BIGINT NOT NULL UNIQUE,
  titulo VARCHAR(160) NOT NULL,
  url VARCHAR(255) NOT NULL,
  duracion_seg INT,
  activo TINYINT(1) NOT NULL DEFAULT 1,
  CONSTRAINT fk_video_minijuego FOREIGN KEY (minijuego_id) REFERENCES minijuegos(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS piezas (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  minijuego_id BIGINT NOT NULL,
  nombre VARCHAR(120) NOT NULL,
  slot_key VARCHAR(40) NOT NULL,
  pos_x INT DEFAULT 0,
  pos_y INT DEFAULT 0,
  CONSTRAINT fk_pieza_minijuego FOREIGN KEY (minijuego_id) REFERENCES minijuegos(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS obstaculos (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  minijuego_id BIGINT NOT NULL,
  tipo VARCHAR(40) NOT NULL,
  movible TINYINT(1) NOT NULL DEFAULT 1,
  atenuacion DECIMAL(5,3) NOT NULL DEFAULT 0.300,
  pos_x INT DEFAULT 0,
  pos_y INT DEFAULT 0,
  ancho INT DEFAULT 20,
  alto INT DEFAULT 100,
  CONSTRAINT fk_obstaculo_minijuego FOREIGN KEY (minijuego_id) REFERENCES minijuegos(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS dispositivos (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  minijuego_id BIGINT NOT NULL,
  tipo VARCHAR(40) NOT NULL,
  pos_x INT DEFAULT 0,
  pos_y INT DEFAULT 0,
  barras INT DEFAULT 0,
  CONSTRAINT fk_dispositivo_minijuego FOREIGN KEY (minijuego_id) REFERENCES minijuegos(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- PROGRESO Y INTENTOS
CREATE TABLE IF NOT EXISTS progreso_juego (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  estudiante_id BIGINT NOT NULL,
  minijuego_id BIGINT NOT NULL,
  estado ENUM('BLOQUEADO','DISPONIBLE','PASADO') NOT NULL DEFAULT 'BLOQUEADO',
  iniciado_en DATETIME DEFAULT NULL,
  finalizado_en DATETIME DEFAULT NULL,
  notas TEXT,
  UNIQUE KEY uq_progreso (estudiante_id, minijuego_id),
  CONSTRAINT fk_progreso_estudiante FOREIGN KEY (estudiante_id) REFERENCES estudiantes(usuario_id) ON DELETE CASCADE,
  CONSTRAINT fk_progreso_minijuego FOREIGN KEY (minijuego_id) REFERENCES minijuegos(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS intentos (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  progreso_id BIGINT NOT NULL,
  inicio TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,   -- <-- TIMESTAMP
  fin DATETIME DEFAULT NULL,
  pasos_correctos INT DEFAULT 0,
  pasos_incorrectos INT DEFAULT 0,
  CONSTRAINT fk_intento_progreso FOREIGN KEY (progreso_id) REFERENCES progreso_juego(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
